global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'laravel'
    static_configs:
      - targets: ['laravel:80']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse:8123']

  - job_name: 'meilisearch'
    static_configs:
      - targets: ['meilisearch:7700']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']